### ISSUE TITLE
maybe consider rename the function `validate` to `validate_json`

### ISSUE THREAD

**Issue by Leo-Lee15** [SymbolixAU/jsonify#11]
Hi, 

Thanks for this awesome package!

Since the `validate()` function in `jsonfy` package has conflict with the `validate()` function in `jsonlite`, it would be better to rename the `validate()` function to avoid the conflict. 

Thanks!

**Comment by SymbolixAU** [comment]
Good suggestion. I'll see if I can intercept CRAN before they accept the release.
