### ISSUE TITLE
data.frame() in README needs stringsAsFactors = FALSE

### ISSUE THREAD

**Issue by ChrisMuir** [SymbolixAU/jsonify#13]
I believe the first instance of `data.frame()` in the `README` is in need of `stringsAsFactors = FALSE`. Check it:
```r
n <- 3
df <- data.frame(
  id = 1:n
  , value = sample(letters, size = n, replace = T)
  , val2 = rnorm(n = n)
  , log = sample(c(T,F), size = n, replace = T)
)
jsonify::to_json(df)
#> [1] "[{\"id\":1,\"value\":1,\"val2\":-0.0023638374800030099,\"log\":true},{\"id\":2,\"value\":3,\"val2\":0.19159224135683393,\"log\":false},{\"id\":3,\"value\":2,\"val2\":0.8843791941680114,\"log\":true}]"
#> attr(,"class")
#> [1] "json"
```
The values returned for `value` are `[1, 3, 2]`, when they should be strings. I tried running the code in that example locally and was confused by the return values, took me a while to realize it was only because `df$value` is a factor variable.

**Comment by SymbolixAU** [comment]
how's this https://github.com/SymbolixAU/jsonify#is-it-fast

and this https://github.com/SymbolixAU/jsonify#why-are-there-numbers-in-stead-of-letters

**Comment by ChrisMuir** [comment]
I think that looks great!
