### ISSUE TITLE
digits

### ISSUE THREAD

**Issue by SymbolixAU** [SymbolixAU/jsonify#4]
should numerics be rounded? 

TODO

- [x] NumericVector
- [x] Matrix
- [x] DataFrame
- [x] Lists
- [x] do I need to force to -1?
- [x] do I need to have the `digits = -1` on ALL the `write_value()` function calls?
- [x] use `as.integer()` or `round(x, 0)` on the `digits` argument - currently using `as.integer()`

**Comment by tim-salabim** [comment]
Not by default in IMO. Having an argument to specify the digits is ideal I think. Less digits where they are not important can speed things up and save disk space, but in some place we need a certain precision (e.g. geographic coordinates).
I like the way that `jsonlite::toJSON` handles this. The specification of significant digits via `I()` may be overkill, but having an option to leave them as they are (`NA`) is nice I think.

**Comment by tim-salabim** [comment]
Is there a ETA for this?

**Comment by SymbolixAU** [comment]
I will look at this again in the new year, and am aiming for an update in Feb 19

**Comment by tim-salabim** [comment]
Thanks for the info!

**Comment by SymbolixAU** [comment]
I've made a `digits` branch where I've made a start on this. I had an idea for the solution so wanted to get it down in code before I forgot!

[tests (and examples) are here](https://github.com/SymbolixAU/jsonify/commit/abe7ac77a64f376bb8c831b9f68865cfd4144461#diff-e53292f93d0a59a05b4fd76f0fcae35e)

**Comment by tim-salabim** [comment]
Cool, thanks! Will test as soon as I'm back at a computer

**Comment by tim-salabim** [comment]
This is brilliant! Using `digits = 5` I can now plot 30+ million points. And thanks to **jsonify** it only takes 23 seconds to create the map! 

I am a very happy customer! :-)

**Comment by SymbolixAU** [comment]
Excellent. Looking froward to seeing the result.

**Comment by SymbolixAU** [comment]
Do you need it exposed through `geojsonsf` too?

**Comment by tim-salabim** [comment]
Yes, that would be perfect thanks!
