### ISSUE TITLE
Type Mapping document

### ISSUE THREAD

**Issue by JosiahParry** [SymbolixAU/jsonify#74]
I understand that type mapping happens at the C++ level. It would be super helpful if there was either a document that could inform users what R object types are cast to what JSON types or, alternatively, a function that would take a prototype input (e.g. list) and return the type mappings in a list.

**Comment by dcooley** [comment]
Is this the type of thing you're after - https://symbolixau.github.io/jsonify/articles/jsonify.html ?

**Comment by JosiahParry** [comment]
That was closer! I'm curious about R -> json type mapping—particularly for objects that aren't of the base classes numeric, integer, character, logical, and list. 

Take for example a wk_crc `circle <- wk::crc(1, 2, 3)`. I suspect that jsonify strips any auxiliary non-base types, is that right? 

``` r
circle <- wk::crc(1, 2, 3)
class(circle)
#> [1] "wk_crc"  "wk_rcrd"

circle
#> <wk_crc[1]>
#> [1] [1 2, r = 3]
as.numeric(circle)
#> [1] 1 2 3
unclass(circle)
#> $x
#> [1] 1
#> 
#> $y
#> [1] 2
#> 
#> $r
#> [1] 3
typeof(circle)
#> [1] "list"
```
