### ISSUE TITLE
Big integers (overflow)

### ISSUE THREAD

**Issue by allmannm** [SymbolixAU/jsonify#81]
Hey,

is there any way to solve this (probable) integer overflow issue? E.g.:

```
library(jsonify)

json_str <- '{"value" : 5500000000}'
json_obj <- as.json(json_str)
```
 and 

```
> from_json(json_obj)$value
[1] 1205032704
```

Thanks in advance for your response.

**Comment by dcooley** [comment]
Yes there probably is a way to handle this internally, but will need some thinking about.

As a workaround you need to explicitly use a 'Numeric'

```
library(jsonify)

json_str <- '{"value" : 5500000000.0}'
json_obj <- as.json(json_str)
from_json(json_obj)$value

# [1] 5.5e+09
```

**Comment by allmannm** [comment]
thanks for the fast response. The workaround works perfectly whenever I create new JSON files. Do know any workaround when reading already existing ones from storage?

**Comment by dcooley** [comment]
I've just pushed a commit to master with a fix (and [test](https://github.com/SymbolixAU/jsonify/blob/master/tests/testthat/test-from_json.R#L20)). This should work when reading from a file too.

Also, a note on your code: you don't need the `as.json()` step, `from_json()` will handle the string

```r
json_str <- '{"value" : 5500000000}'
from_json(json_obj)$value
```

**Comment by allmannm** [comment]
thanks a lot for this fast fix! Everything works fine for me.

Regarding your note, in my original coding I do not use the `as.json()` function, but for creating a quick reproducible example, I got things a little messed up. Sorry for this.
